### ISSUE TITLE
[BUG]Write out file will not success and no error throwed (because the tmp file name is too long)

### ISSUE THREAD

**Issue by ppoo24** [vbauer/manet#10]
I've found this BUG under Windows 7 64bit, stripping out the raw shell command (manual piece together):
```shell
phantomjs "E:\\Program Files (x86)\\nodejs\\node_modules\\manet\\src\\scripts\\screenshot.js" "eyJ1cmwiOiJodHRwOi8vengyNTBsb2NhbC5jb206MzAwMC9tYWdpY3Blbi9hcHAvIy9tYWluL2luZGV4P2l0ZW1MYXlJZD0zJnNuYXBzaG90PTEmX19hPTk2QjcxRDkyOEJFRTM4NkUxMTA2MjFCRUIzN0RGRkYyIiwiZm9ybWF0IjoicG5nIiwid2lkdGgiOjE5MjAsImhlaWdodCI6MTA4MCwic2VsZWN0b3IiOiIjbWFpbi1hcmVhIn0=" "C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\yJ1cmwiOiJodHRwOi8vengyNTBsb2NhbC5jb206MzAwMC9tYWdpY3Blbi9hcHAvIy9tYWluL2luZGV4P2l0ZW1MYXlJZD0zJnNuYXBzaG90PTEmX19hPTk2QjcxRDkyOEJFRTM4NkUxMTA2MjFCRUIzN0RGRkYyIiwiZm9ybWF0IjoicG5nIiwid2lkdGgiOjE5MjAsImhlaWdodCI6MTA4MCwic2VsZWN0b3IiOiIjbWFpbi1hcmVhIn0=.png"
```
this command will run successfully with no extra exceptions, but the temp file will not be writed, so when visit manet, manet will send 404.
searched, linux && windows both have the file name length limiting, so we should keep the temp file name's length, and add a prefix word + a random word + timestamp is well.

at `manet/src/capture.js` Line 18, i modified:
```js
function outputFile(options, conf, base64) {
    var format = options.format || DEF_FORMAT;
	//zcs=>The base64's length is too long for a file name, so we should fix the length
	var filename = 'manettemp_' + (base64 + '').substr(-20) + '_' + Date.now() + '_' + Math.floor(Math.random() * (999999 - 100000) + 100000);
	//<=zcs
    // return conf.storage + path.sep + base64 + '.' + format; //zcs=old line
	return conf.storage + path.sep + filename + '.' + format;
}
```

**Comment by sgates** [comment]
Has anyone done any work with this? Just hit same problem, and it's a show stopper for using Manet with our app - which is sad because this is otherwise a GREAT app. Found this: https://github.com/dbushell/grunt-svg2png/issues/17 - https://github.com/dbushell/grunt-svg2png/pull/25 , not sure if helpful?

**Comment by ppoo24** [comment]
@sgates as I mentioned above, u could rename the file name in your way as a temporary solution for the problem

**Comment by sgates** [comment]
@ppoo24 yeah, I think I'm going to go ahead and do that. Tried with a simple MD5, I think it'll work for me. Not too worried about Manet caching since I will be caching myself and only using Manet for fresh pulls. Thanks for the advice!

**Comment by cdunlap** [comment]
I ran into this issue on Linux as well. Rather than MD5 (due to collisions) or Base64 (due to length), would [UUID v4](http://www.ietf.org/rfc/rfc4122.txt) be a better option? They're more unique than MD5, shorter than Base64, and have a collision probability of [~50% if one billion of them were created every second for 100 years](http://en.wikipedia.org/wiki/Universally_unique_identifier#Version_4_.28random.29) which would surely be unique enough for cache purposes I would think. There's a [Node library](https://www.npmjs.com/package/uuid) for generating them.

**Comment by cdunlap** [comment]
There's always SHA-1 or SHA-2. SHA-1 hasn't had any collisions yet as far as I can tell.

**Comment by vbauer** [comment]
Fixed here: https://github.com/vbauer/manet/pull/39
Solution with database could be implemented a little bit later.
